/**
 * Fiches conseil par type de menace.
 * Chaque fiche contient des instructions claires et sourcées.
 */

export interface ThreatGuide {
  event_type: string
  title_fr: string
  title_en: string
  icon: string
  actions_fr: string[]
  actions_en: string[]
  source: string
}

export const THREAT_GUIDES: ThreatGuide[] = [
  {
    event_type: 'EQ',
    title_fr: 'Seisme',
    title_en: 'Earthquake',
    icon: '🌍',
    actions_fr: [
      'A l\'interieur : abritez-vous sous une table solide, loin des fenetres',
      'A l\'exterieur : eloignez-vous des batiments, cables electriques et ponts',
      'Apres la secousse : coupez gaz et electricite, evacuez si le batiment est endommage',
      'Preparez-vous aux repliques dans les heures suivantes',
      'N\'utilisez pas les ascenseurs',
    ],
    actions_en: [
      'Indoors: take cover under a sturdy table, away from windows',
      'Outdoors: move away from buildings, power lines and bridges',
      'After the shaking: shut off gas and electricity, evacuate if building is damaged',
      'Prepare for aftershocks in the following hours',
      'Do not use elevators',
    ],
    source: 'SGDSN - Guide de preparation aux risques, p.12',
  },
  {
    event_type: 'FL',
    title_fr: 'Inondation',
    title_en: 'Flood',
    icon: '🌊',
    actions_fr: [
      'Montez dans les etages superieurs, jamais au sous-sol',
      'Coupez electricite et gaz si possible',
      'Ne traversez jamais une zone inondee a pied ou en voiture (30cm suffisent)',
      'Ecoutez la radio pour les consignes officielles',
      'Preparez votre kit d\'evacuation et vos documents',
    ],
    actions_en: [
      'Move to upper floors, never to the basement',
      'Turn off electricity and gas if possible',
      'Never cross a flooded area on foot or by car (30cm is enough)',
      'Listen to the radio for official instructions',
      'Prepare your evacuation kit and documents',
    ],
    source: 'Plan ORSEC - Inondations',
  },
  {
    event_type: 'TC',
    title_fr: 'Cyclone tropical',
    title_en: 'Tropical Cyclone',
    icon: '🌀',
    actions_fr: [
      'Restez a l\'interieur, loin des fenetres et portes vitrees',
      'Renforcez portes et volets, protegez les fenetres avec du ruban',
      'Stockez eau potable (remplissez baignoire/seaux)',
      'L\'oeil du cyclone : le calme est temporaire, ne sortez pas',
      'Apres le passage : attention aux cables electriques au sol et debris',
    ],
    actions_en: [
      'Stay indoors, away from windows and glass doors',
      'Reinforce doors and shutters, tape windows',
      'Stock drinking water (fill bathtub/buckets)',
      'The eye of the storm: calm is temporary, do not go outside',
      'After the storm: watch for downed power lines and debris',
    ],
    source: 'Meteo-France - Vigilance cyclonique',
  },
  {
    event_type: 'NUCLEAR',
    title_fr: 'Menace nucleaire',
    title_en: 'Nuclear Threat',
    icon: '☢️',
    actions_fr: [
      'Entrez dans le batiment en dur le plus proche (pas de vehicule)',
      'Fermez portes, fenetres, bouches d\'aeration, calfeutrez avec du ruban',
      'Prenez les comprimes d\'iode UNIQUEMENT sur instruction des autorites',
      'Ne mangez/buvez rien d\'exterieur, utilisez vos reserves',
      'Si vous etiez dehors : retirez vos vetements, douchez-vous sans frotter',
      'Ecoutez France Inter (162 kHz) ou France Info',
    ],
    actions_en: [
      'Enter the nearest solid building (not a vehicle)',
      'Close doors, windows, vents, seal with tape',
      'Take iodine tablets ONLY when instructed by authorities',
      'Do not eat/drink anything from outside, use your supplies',
      'If you were outside: remove clothing, shower without scrubbing',
      'Listen to official radio channels',
    ],
    source: 'ASN - Instruction iode / Plan PPI',
  },
  {
    event_type: 'CHEMICAL',
    title_fr: 'Menace chimique',
    title_en: 'Chemical Threat',
    icon: '⚗️',
    actions_fr: [
      'Confinez-vous : fermez tout, calfeutrez avec des linges humides',
      'Si a l\'exterieur : respirez a travers un tissu humide, fuyez perpendiculairement au vent',
      'Ne touchez aucune substance inconnue',
      'Retirez vos vetements contamines et mettez-les dans un sac plastique',
      'Alertez les secours (18 ou 112)',
    ],
    actions_en: [
      'Shelter in place: close everything, seal with wet cloths',
      'If outside: breathe through a wet cloth, flee perpendicular to wind',
      'Do not touch any unknown substance',
      'Remove contaminated clothing and put in a plastic bag',
      'Call emergency services (18 or 112)',
    ],
    source: 'SGDSN - Plan ORSEC TMD',
  },
  {
    event_type: 'CONFLICT',
    title_fr: 'Conflit arme',
    title_en: 'Armed Conflict',
    icon: '⚔️',
    actions_fr: [
      'Restez a l\'ecart des zones de combat et des batiments officiels',
      'Gardez vos documents d\'identite sur vous en permanence',
      'Identifiez les abris les plus proches (metro, parking souterrain)',
      'Preparez un sac d\'evacuation pret a partir',
      'Suivez les consignes des autorites civiles et militaires',
      'En cas de tir : allongez-vous, protegez votre tete, rampez vers un abri',
    ],
    actions_en: [
      'Stay away from combat zones and official buildings',
      'Keep your ID documents on you at all times',
      'Identify nearby shelters (metro, underground parking)',
      'Prepare a go-bag ready to leave',
      'Follow civil and military authority instructions',
      'Under fire: lie flat, protect your head, crawl to shelter',
    ],
    source: 'SGDSN - Plan Vigipirate',
  },
  {
    event_type: 'HEALTH',
    title_fr: 'Crise sanitaire',
    title_en: 'Health Crisis',
    icon: '🦠',
    actions_fr: [
      'Respectez les gestes barrieres : masque, lavage des mains, distance',
      'Limitez les deplacements non essentiels',
      'Stockez 7 jours de medicaments et nourriture',
      'Desinfectez les surfaces frequemment touchees',
      'Suivez les consignes de l\'ARS et du ministere de la Sante',
    ],
    actions_en: [
      'Follow barrier measures: mask, handwashing, distancing',
      'Limit non-essential travel',
      'Stock 7 days of medication and food',
      'Disinfect frequently touched surfaces',
      'Follow health authority guidelines',
    ],
    source: 'ARS / Ministere de la Sante',
  },
  {
    event_type: 'WF',
    title_fr: 'Feu de foret',
    title_en: 'Wildfire',
    icon: '🔥',
    actions_fr: [
      'Evacuez des l\'alerte, n\'attendez pas',
      'Fermez portes, fenetres et volets avant de partir',
      'Fuyez perpendiculairement a la direction du vent',
      'Ne tentez jamais d\'eteindre un feu de foret vous-meme',
      'Si piege : refugiez-vous dans un batiment en dur, pas dans un vehicule',
    ],
    actions_en: [
      'Evacuate as soon as alerted, do not wait',
      'Close doors, windows and shutters before leaving',
      'Flee perpendicular to wind direction',
      'Never attempt to fight a wildfire yourself',
      'If trapped: shelter in a solid building, not in a vehicle',
    ],
    source: 'SDIS - Prevention feux de foret',
  },
  {
    event_type: 'VO',
    title_fr: 'Eruption volcanique',
    title_en: 'Volcanic Eruption',
    icon: '🌋',
    actions_fr: [
      'Evacuez la zone d\'exclusion immediatement',
      'Protegez-vous des cendres : masque FFP2, lunettes, manches longues',
      'Fuyez face au vent pour eviter le panache de cendres',
      'Ne conduisez pas dans un nuage de cendres (visibilite nulle)',
      'Nettoyez les cendres de votre toit (risque d\'effondrement)',
    ],
    actions_en: [
      'Evacuate the exclusion zone immediately',
      'Protect from ash: FFP2 mask, goggles, long sleeves',
      'Flee upwind to avoid the ash plume',
      'Do not drive in an ash cloud (zero visibility)',
      'Clean ash from your roof (collapse risk)',
    ],
    source: 'OVSG / BRGM - Risque volcanique',
  },
  {
    event_type: 'DR',
    title_fr: 'Secheresse',
    title_en: 'Drought',
    icon: '☀️',
    actions_fr: [
      'Economisez l\'eau : bains courts, pas d\'arrosage',
      'Stockez de l\'eau potable supplementaire',
      'Surveillez les restrictions prefectorales',
      'Risque de feux de foret accru : vigilance maximale',
    ],
    actions_en: [
      'Conserve water: short showers, no watering',
      'Stock extra drinking water',
      'Monitor government water restrictions',
      'Increased wildfire risk: maximum vigilance',
    ],
    source: 'Ministere de la Transition ecologique',
  },
  {
    event_type: 'NUCLEAR',
    title_fr: 'Menace nucleaire',
    title_en: 'Nuclear threat',
    icon: '☢️',
    actions_fr: [
      'Mettez-vous a l\'abri dans un batiment en dur (murs epais, sous-sol ideal)',
      'Fermez toutes les ouvertures : portes, fenetres, ventilation, cheminee',
      'Prenez des comprimes d\'iode UNIQUEMENT sur consigne des autorites',
      'N\'allez pas chercher vos enfants a l\'ecole, ils sont pris en charge',
      'Ecoutez la radio (France Inter, France Info) pour les consignes officielles',
      'Ne consommez pas d\'aliments ou d\'eau du robinet non valides par les autorites',
    ],
    actions_en: [
      'Shelter in a solid building (thick walls, basement ideal)',
      'Close all openings: doors, windows, ventilation, chimneys',
      'Take iodine tablets ONLY when instructed by authorities',
      'Do not pick up children from school, they are being cared for',
      'Listen to radio for official instructions',
      'Do not consume food or water not validated by authorities',
    ],
    source: 'ASN / IRSN - Plan particulier d\'intervention nucleaire',
  },
  {
    event_type: 'CHEMICAL',
    title_fr: 'Risque chimique',
    title_en: 'Chemical hazard',
    icon: '🧪',
    actions_fr: [
      'Confinement immediat : entrez dans un batiment, fermez tout',
      'Bouchez les aérations avec du ruban adhesif et des linges mouilles',
      'Ne fumez pas, pas de flamme nue',
      'Eloignez-vous de la zone si vous etes en exterieur (vent dans le dos)',
      'En cas de contact : retirez les vetements contamines, lavez-vous abondamment',
      'Attendez le signal de fin d\'alerte avant de sortir',
    ],
    actions_en: [
      'Shelter immediately: go inside, close everything',
      'Seal vents with tape and wet cloths',
      'No smoking, no open flames',
      'Move away from the area if outdoors (wind at your back)',
      'If exposed: remove contaminated clothes, wash thoroughly',
      'Wait for the all-clear signal before going outside',
    ],
    source: 'SGDSN / Prefectures - Risque industriel SEVESO',
  },
  {
    event_type: 'SHORTAGE',
    title_fr: 'Penurie',
    title_en: 'Shortage',
    icon: '📦',
    actions_fr: [
      'Verifiez vos reserves d\'eau (6L/personne minimum) et de nourriture (3 jours)',
      'Faites le plein de carburant des que possible si penurie annoncee',
      'Privilegiez les circuits courts et marches locaux',
      'Ne cedez pas a la panique : les achats massifs aggravent la penurie',
      'Gardez du liquide (especes) en cas de panne des terminaux de paiement',
      'Surveillez les communications officielles pour les plans de rationnement',
    ],
    actions_en: [
      'Check your water supply (6L/person minimum) and food (3 days)',
      'Fill up fuel as soon as possible if shortage announced',
      'Prefer local supply chains and markets',
      'Don\'t panic buy: mass purchases worsen shortages',
      'Keep cash in case payment terminals go down',
      'Monitor official communications for rationing plans',
    ],
    source: 'SGDSN - Guide des comportements en situation de crise',
  },
  {
    event_type: 'CYBER',
    title_fr: 'Cyberattaque',
    title_en: 'Cyber attack',
    icon: '💻',
    actions_fr: [
      'Deconnectez les appareils suspects du reseau (WiFi et cable)',
      'Ne payez jamais de rancon en cas de ransomware',
      'Changez vos mots de passe depuis un appareil non compromis',
      'Sauvegardez vos donnees critiques sur un support deconnecte',
      'Signalez l\'incident sur cybermalveillance.gouv.fr',
      'Surveillez vos comptes bancaires pour des mouvements suspects',
    ],
    actions_en: [
      'Disconnect suspicious devices from network (WiFi and cable)',
      'Never pay ransom in case of ransomware',
      'Change passwords from a non-compromised device',
      'Back up critical data on a disconnected drive',
      'Report the incident to relevant authorities',
      'Monitor bank accounts for suspicious activity',
    ],
    source: 'ANSSI / cybermalveillance.gouv.fr',
  },
  {
    event_type: 'UNREST',
    title_fr: 'Troubles civils',
    title_en: 'Civil unrest',
    icon: '🚧',
    actions_fr: [
      'Evitez les zones de rassemblement et manifestations',
      'Restez informe via les medias officiels et les reseaux sociaux',
      'Ne sortez pas si un couvre-feu est en vigueur',
      'Gardez vos documents d\'identite sur vous en permanence',
      'Preparez un sac d\'evacuation rapide (documents, eau, telephone)',
      'Signalez toute situation dangereuse au 17 (police) ou 112',
    ],
    actions_en: [
      'Avoid gathering areas and protest zones',
      'Stay informed via official media and social networks',
      'Do not go outside if a curfew is in effect',
      'Keep your ID documents on you at all times',
      'Prepare a quick evacuation bag (documents, water, phone)',
      'Report dangerous situations to emergency services (112)',
    ],
    source: 'Ministere de l\'Interieur / Prefectures',
  },
]

export function getGuideForEvent(eventType: string): ThreatGuide | undefined {
  return THREAT_GUIDES.find((g) => g.event_type === eventType)
}
